//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GM.Identity.Sample.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GM.Identity.Sample.Common.Resources.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        public static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Scope.
        /// </summary>
        public static string ClientScope {
            get {
                return ResourceManager.GetString("ClientScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Session.
        /// </summary>
        public static string ClientSession {
            get {
                return ResourceManager.GetString("ClientSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation.
        /// </summary>
        public static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id of Operation.
        /// </summary>
        public static string OperationId {
            get {
                return ResourceManager.GetString("OperationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission.
        /// </summary>
        public static string Permission {
            get {
                return ResourceManager.GetString("Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id of Permission.
        /// </summary>
        public static string PermissionId {
            get {
                return ResourceManager.GetString("PermissionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id of Role.
        /// </summary>
        public static string RoleId {
            get {
                return ResourceManager.GetString("RoleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Permission.
        /// </summary>
        public static string RolePermission {
            get {
                return ResourceManager.GetString("RolePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope.
        /// </summary>
        public static string Scope {
            get {
                return ResourceManager.GetString("Scope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id of Scope.
        /// </summary>
        public static string ScopeId {
            get {
                return ResourceManager.GetString("ScopeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope Operation.
        /// </summary>
        public static string ScopeOperation {
            get {
                return ResourceManager.GetString("ScopeOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role of User.
        /// </summary>
        public static string UserRole {
            get {
                return ResourceManager.GetString("UserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Session.
        /// </summary>
        public static string UserSession {
            get {
                return ResourceManager.GetString("UserSession", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Two-Factor Authentication Type.
        /// </summary>
        public static string TwoFactorAuthType {
            get {
                return ResourceManager.GetString("TwoFactorAuthType", resourceCulture);
            }
        }
        public static string ApiKey {
            get {
                return ResourceManager.GetString("ApiKey", resourceCulture);
            }
        }

        public static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }

        public static string BackchannelLogoutUri {
            get {
                return ResourceManager.GetString("BackchannelLogoutUri", resourceCulture);
            }
        }

        public static string Block {
            get {
                return ResourceManager.GetString("Block", resourceCulture);
            }
        }

        public static string ChannelId {
            get {
                return ResourceManager.GetString("ChannelId", resourceCulture);
            }
        }

        public static string ClientId {
            get {
                return ResourceManager.GetString("ClientId", resourceCulture);
            }
        }

        public static string ClientName {
            get {
                return ResourceManager.GetString("ClientName", resourceCulture);
            }
        }

        public static string ClientScopes {
            get {
                return ResourceManager.GetString("ClientScopes", resourceCulture);
            }
        }

        public static string ClientSecret {
            get {
                return ResourceManager.GetString("ClientSecret", resourceCulture);
            }
        }

        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }

        public static string CodeChallenge {
            get {
                return ResourceManager.GetString("CodeChallenge", resourceCulture);
            }
        }

        public static string CodeChallengeMethod {
            get {
                return ResourceManager.GetString("CodeChallengeMethod", resourceCulture);
            }
        }

        public static string CodeVerifier {
            get {
                return ResourceManager.GetString("CodeVerifier", resourceCulture);
            }
        }

        public static string Codes {
            get {
                return ResourceManager.GetString("Codes", resourceCulture);
            }
        }

        public static string ConfirmationType {
            get {
                return ResourceManager.GetString("ConfirmationType", resourceCulture);
            }
        }

        public static string Consent {
            get {
                return ResourceManager.GetString("Consent", resourceCulture);
            }
        }

        public static string ConsentType {
            get {
                return ResourceManager.GetString("ConsentType", resourceCulture);
            }
        }

        public static string CorrelationId {
            get {
                return ResourceManager.GetString("CorrelationId", resourceCulture);
            }
        }

        public static string CredentialId {
            get {
                return ResourceManager.GetString("CredentialId", resourceCulture);
            }
        }

        public static string CultureCode {
            get {
                return ResourceManager.GetString("CultureCode", resourceCulture);
            }
        }

        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }

        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }

        public static string DeviceCode {
            get {
                return ResourceManager.GetString("DeviceCode", resourceCulture);
            }
        }

        public static string DocumentVersion {
            get {
                return ResourceManager.GetString("DocumentVersion", resourceCulture);
            }
        }

        public static string EventType {
            get {
                return ResourceManager.GetString("EventType", resourceCulture);
            }
        }

        public static string ExpiresAt {
            get {
                return ResourceManager.GetString("ExpiresAt", resourceCulture);
            }
        }

        public static string FrontchannelLogoutUri {
            get {
                return ResourceManager.GetString("FrontchannelLogoutUri", resourceCulture);
            }
        }

        public static string GrantType {
            get {
                return ResourceManager.GetString("GrantType", resourceCulture);
            }
        }

        public static string IdTokenHint {
            get {
                return ResourceManager.GetString("IdTokenHint", resourceCulture);
            }
        }

        public static string IdempotencyKey {
            get {
                return ResourceManager.GetString("IdempotencyKey", resourceCulture);
            }
        }

        public static string IpAddress {
            get {
                return ResourceManager.GetString("IpAddress", resourceCulture);
            }
        }

        public static string IsExpired {
            get {
                return ResourceManager.GetString("IsExpired", resourceCulture);
            }
        }

        public static string IsRevoked {
            get {
                return ResourceManager.GetString("IsRevoked", resourceCulture);
            }
        }

        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }

        public static string Nonce {
            get {
                return ResourceManager.GetString("Nonce", resourceCulture);
            }
        }

        public static string NotificationType {
            get {
                return ResourceManager.GetString("NotificationType", resourceCulture);
            }
        }

        public static string OccurredOn {
            get {
                return ResourceManager.GetString("OccurredOn", resourceCulture);
            }
        }

        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }

        public static string Payload {
            get {
                return ResourceManager.GetString("Payload", resourceCulture);
            }
        }

        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }

        public static string PostLogoutRedirectUri {
            get {
                return ResourceManager.GetString("PostLogoutRedirectUri", resourceCulture);
            }
        }

        public static string Prompt {
            get {
                return ResourceManager.GetString("Prompt", resourceCulture);
            }
        }

        public static string PublicKeySpkiBase64 {
            get {
                return ResourceManager.GetString("PublicKeySpkiBase64", resourceCulture);
            }
        }

        public static string RedirectUri {
            get {
                return ResourceManager.GetString("RedirectUri", resourceCulture);
            }
        }

        public static string RedirectUris {
            get {
                return ResourceManager.GetString("RedirectUris", resourceCulture);
            }
        }

        public static string RefreshToken {
            get {
                return ResourceManager.GetString("RefreshToken", resourceCulture);
            }
        }

        public static string RequireConsent {
            get {
                return ResourceManager.GetString("RequireConsent", resourceCulture);
            }
        }

        public static string RevokedAt {
            get {
                return ResourceManager.GetString("RevokedAt", resourceCulture);
            }
        }

        public static string RolePermissions {
            get {
                return ResourceManager.GetString("RolePermissions", resourceCulture);
            }
        }

        public static string ScopeOperations {
            get {
                return ResourceManager.GetString("ScopeOperations", resourceCulture);
            }
        }

        public static string Secret {
            get {
                return ResourceManager.GetString("Secret", resourceCulture);
            }
        }

        public static string SessionId {
            get {
                return ResourceManager.GetString("SessionId", resourceCulture);
            }
        }

        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }

        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }

        public static string TenantId {
            get {
                return ResourceManager.GetString("TenantId", resourceCulture);
            }
        }

        public static string Token {
            get {
                return ResourceManager.GetString("Token", resourceCulture);
            }
        }

        public static string TokenTypeHint {
            get {
                return ResourceManager.GetString("TokenTypeHint", resourceCulture);
            }
        }

        public static string TwoFactorAuthTypeIds {
            get {
                return ResourceManager.GetString("TwoFactorAuthTypeIds", resourceCulture);
            }
        }

        public static string UserAgent {
            get {
                return ResourceManager.GetString("UserAgent", resourceCulture);
            }
        }

        public static string UserCode {
            get {
                return ResourceManager.GetString("UserCode", resourceCulture);
            }
        }

        public static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }

        public static string UserIds {
            get {
                return ResourceManager.GetString("UserIds", resourceCulture);
            }
        }

        public static string UserRoles {
            get {
                return ResourceManager.GetString("UserRoles", resourceCulture);
            }
        }

    }
}
